# Site settings
title: timswilson.com
description: My personal website
url: "https://timswilson.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

# Plugins
plugins:
  - jekyll-seo-tag

# Defaults
defaults:
  - scope:
      path: "*"
    values:
      layout: default

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - tailwind.config.js
  - assets/css/input.css
