# Site settings
title: timswilson.com
description: My personal website
url: "https://timswilson.com"

# Build settings
markdown: kramdown

# Defaults
defaults:
  - scope:
      path: "*"
    values:
      layout: default

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - tailwind.config.js
  - assets/css/input.css
